# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        MainWindow.setMinimumSize(QtCore.QSize(600, 300))
        MainWindow.setMaximumSize(QtCore.QSize(600, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icono/icono.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo_cohemo = QtWidgets.QLabel(self.centralwidget)
        self.logo_cohemo.setGeometry(QtCore.QRect(5, 0, 400, 90))
        self.logo_cohemo.setObjectName("logo_cohemo")
        self.pushButton_generar_grafica = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_generar_grafica.setGeometry(QtCore.QRect(480, 230, 100, 30))
        self.pushButton_generar_grafica.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_generar_grafica.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_generar_grafica.setStyleSheet("background-color: rgb(0, 16, 103);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_generar_grafica.setObjectName("pushButton_generar_grafica")
        self.textBrowser_ruta_entrada = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_ruta_entrada.setGeometry(QtCore.QRect(20, 110, 450, 30))
        self.textBrowser_ruta_entrada.setMinimumSize(QtCore.QSize(450, 30))
        self.textBrowser_ruta_entrada.setMaximumSize(QtCore.QSize(450, 30))
        self.textBrowser_ruta_entrada.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_ruta_entrada.setObjectName("textBrowser_ruta_entrada")
        self.textBrowser_ruta_salida = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_ruta_salida.setGeometry(QtCore.QRect(20, 160, 450, 30))
        self.textBrowser_ruta_salida.setMinimumSize(QtCore.QSize(450, 30))
        self.textBrowser_ruta_salida.setMaximumSize(QtCore.QSize(450, 30))
        self.textBrowser_ruta_salida.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_ruta_salida.setObjectName("textBrowser_ruta_salida")
        self.pushButton_abrir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_abrir.setGeometry(QtCore.QRect(480, 110, 100, 30))
        self.pushButton_abrir.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_abrir.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_abrir.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.pushButton_abrir.setObjectName("pushButton_abrir")
        self.pushButton_cambiar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cambiar.setGeometry(QtCore.QRect(480, 160, 100, 30))
        self.pushButton_cambiar.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_cambiar.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_cambiar.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.pushButton_cambiar.setObjectName("pushButton_cambiar")
        self.label_ruta_entrada = QtWidgets.QLabel(self.centralwidget)
        self.label_ruta_entrada.setGeometry(QtCore.QRect(20, 90, 450, 20))
        self.label_ruta_entrada.setMinimumSize(QtCore.QSize(450, 20))
        self.label_ruta_entrada.setMaximumSize(QtCore.QSize(450, 20))
        self.label_ruta_entrada.setObjectName("label_ruta_entrada")
        self.label_ruta_salida = QtWidgets.QLabel(self.centralwidget)
        self.label_ruta_salida.setGeometry(QtCore.QRect(20, 140, 450, 20))
        self.label_ruta_salida.setMinimumSize(QtCore.QSize(450, 20))
        self.label_ruta_salida.setMaximumSize(QtCore.QSize(450, 20))
        self.label_ruta_salida.setObjectName("label_ruta_salida")
        self.comboBox_desplegable_graficas = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_desplegable_graficas.setGeometry(QtCore.QRect(20, 230, 450, 30))
        self.comboBox_desplegable_graficas.setMinimumSize(QtCore.QSize(450, 30))
        self.comboBox_desplegable_graficas.setMaximumSize(QtCore.QSize(450, 30))
        self.comboBox_desplegable_graficas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_desplegable_graficas.setObjectName("comboBox_desplegable_graficas")
        self.comboBox_desplegable_graficas.addItem("")
        self.comboBox_desplegable_graficas.addItem("")
        self.comboBox_desplegable_graficas.addItem("")
        self.comboBox_desplegable_graficas.addItem("")
        self.comboBox_desplegable_graficas.addItem("")
        self.comboBox_desplegable_graficas.addItem("")
        self.comboBox_desplegable_graficas.addItem("")
        self.label_tipo_grafica = QtWidgets.QLabel(self.centralwidget)
        self.label_tipo_grafica.setGeometry(QtCore.QRect(20, 209, 450, 20))
        self.label_tipo_grafica.setMinimumSize(QtCore.QSize(450, 20))
        self.label_tipo_grafica.setMaximumSize(QtCore.QSize(450, 20))
        self.label_tipo_grafica.setObjectName("label_tipo_grafica")
        self.label_mensajes = QtWidgets.QLabel(self.centralwidget)
        self.label_mensajes.setGeometry(QtCore.QRect(20, 260, 451, 20))
        self.label_mensajes.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_mensajes.setText("")
        self.label_mensajes.setObjectName("label_mensajes")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GMP - Generador de gráficas"))
        self.logo_cohemo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/imagen/Imagen.png\"/></p></body></html>"))
        self.pushButton_generar_grafica.setText(_translate("MainWindow", "Generar gráfica"))
        self.textBrowser_ruta_entrada.setToolTip(_translate("MainWindow", "Ruta del archivo del ensayo"))
        self.textBrowser_ruta_salida.setToolTip(_translate("MainWindow", "Carpeta donde se guardan las gráficas generadas"))
        self.pushButton_abrir.setText(_translate("MainWindow", "Abrir"))
        self.pushButton_cambiar.setText(_translate("MainWindow", "Cambiar"))
        self.label_ruta_entrada.setText(_translate("MainWindow", "Ruta de entrada"))
        self.label_ruta_salida.setText(_translate("MainWindow", "Guardar en"))
        self.comboBox_desplegable_graficas.setToolTip(_translate("MainWindow", "Selecciona el tipo de gráfica que desea generar"))
        self.comboBox_desplegable_graficas.setItemText(0, _translate("MainWindow", "Conexión/Desconexión de ventiladores"))
        self.comboBox_desplegable_graficas.setItemText(1, _translate("MainWindow", "Conexión/Desconexión Kick-Down"))
        self.comboBox_desplegable_graficas.setItemText(2, _translate("MainWindow", "Pérdida de Potencia-Temperatura"))
        self.comboBox_desplegable_graficas.setItemText(3, _translate("MainWindow", "Desconexión 1200rpm"))
        self.comboBox_desplegable_graficas.setItemText(4, _translate("MainWindow", "Desconexión 1400rpm"))
        self.comboBox_desplegable_graficas.setItemText(5, _translate("MainWindow", "Prueba del regulador"))
        self.comboBox_desplegable_graficas.setItemText(6, _translate("MainWindow", "Completo"))
        self.label_tipo_grafica.setText(_translate("MainWindow", "Tipo de gráfica"))
import icono_rc
import imagen_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
